import shutil
import os
import concurrent.futures
import tempfile
import time
import numpy as np
import pandas as pd
import re
import ast
import json
import dateutil.tz as tz
from enum import Enum
from logging import Logger
from functools import partialmethod
from configparser import ConfigParser
from datetime import datetime, date, timedelta
from typing import Tuple
from airflow_pipelines.airflow_pipeline_adapters import AirflowStageMixin
from pipelines.DataPipeline import BaseStage, StageResult, PipelineContext
from storage.file.FileStorage import CSVVectorizedStorage
from commons.ftp.FtpWrapper import FtpWrapper, FtpWrapperParameters
from commons.utils.FileUtils import extract_with_7zip
from commons.utils.DateAndTimeUtils import prev_business_day
from commons.utils.TextUtils import  configparser_to_json
# The cdf bar schema - autogenerated
from schemas.schemas_py.marketdata.cdf_bar import MarketDataBar

# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------
# Collection of Kibot dedicate utils
# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------

class KibotRunType(Enum):
    Equity = 0
    Etf = 1


def extract_and_validate_date(path):
    # Extract the 8-digit pattern before .exe
    match = re.search(r'(\d{8})\.exe$', path)
    if not match:
        return None  # No valid 8-digit sequence found
    date_str = match.group(1)
    # Validate the date format (YYYYMMDD)
    try:
        datetime.strptime(date_str, "%Y%m%d")
        return date_str  # It's a valid date
    except ValueError:
        return None  # Invalid date (e.g., 20230230)


def _safe_dir_component(name: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", name).strip("_")
    return safe or "unknown"


def _extract_subdir_from_archive(archive_in: str) -> str:
    # archive_in: .../<All Stocks|All ETFs>/Daily/YYYYMMDD.exe
    parent = os.path.basename(os.path.dirname(os.path.dirname(archive_in)))
    return _safe_dir_component(parent)


def extract_date(date_str):
    date_str_ = date_str.split('T')[0]
    return datetime.strptime(date_str_,'%Y-%m-%d').date()


def _validate_op(row: list, symbl: str, reportName: str, filter: list, value, op, errors="strict", replace_with=np.nan):
    """
    Check for field <op> value for the fields where filter is True
    row: list of parsed data (the fields)
    filter: list of bools indicating which fields to check
    value: value to compare the field with
    op: operator function of the form op(<field>, <value>) -> bool
    errors: one of "strict" (raise Exception) or "replace" replace with the parameter replace_with
    replace_with: value to replace invalid values, iff errors is "replace"
    """

    # This will raise an exception anst stop the Engne - so we have to update it
    # assert len(row) == len(filter), "filter and row must have the same length"
    if len(row) != len(filter):
        ss = "validate() - Warning on " + symbl + " wrong line - " + str(row)

    assert errors in ["strict", "replace"], "errors must be one of 'strict' or 'replace'"

    result = []
    for i, field in enumerate(row):
        if filter[i] and not op(float(field), value):
            if errors == "strict":
                raise Exception(f"in row: {row}\nvalue {field} is not positive")
            else:
                ss = "validate() - Warning on " + symbl + " line - " + str(row) + " - field: " + str(field)
                result.append(replace_with)
        else:
            result.append(field)

    assert len(result) == len(row)
    return result


def validate(row: list, symbl: str, reportName: str, errors="replace", replace_with=np.nan):
    """
    validate a single row of CDF - Common Data Format
    v2 N.9 - FIELDS - OK
         --------------------------------------------------------------------------------------------
         Date, Time, Open, High, Low, Close, Volume, Vwap, count
         --------------------------------------------------------------------------------------------
    """
    result = _validate_gt(row, symbl, reportName, [False, False, True, True, True, True, False, False, False], 0,
                               errors=errors, replace_with=replace_with)
    result = _validate_ge(result, symbl, reportName,
                               [False, False, False, False, False, False, True, False, False], 0, errors=errors,
                               replace_with=replace_with)
    return result


def strToIso8601TZ(ss : str,HOUR=23, MIN=59, SECS=00):
    # Validate input String
    validateString(ss)
    # convert string to datetime
    dd=datetime.strptime(ss, '%m/%d/%Y')
    # set the Time and ZoneInfo
    dd=dd.replace(hour=HOUR, minute=MIN, second=SECS,tzinfo=tz.gettz('America/New_York'))
    return dd.isoformat()


def validateString(ss : str) :
     try:
         datetime.strptime(ss, '%m/%d/%Y')
     except ValueError:
         raise ValueError("Incorrect data format, should be MM/DD/YYYY passed: "+ ss)


def splitTime(symbl,tt):
    try:
      ttime=tt.split(':')
      if len(ttime)==2 :
         hh=int(ttime[0])
         mm=int(ttime[1])
         return [hh,mm]
      else : raise Exception("Parse::splitTime() - Wrrot to split the Time "+ tt + " Field for "+symbl )
    except Exception as e:
        return [0,0]


def parse(line: str, symb:str)-> list:
    lst=[]
    try:
       if type(line) is bytes:
           ll=line.decode('utf8','ignore').rstrip().split(',')
       else:
           ll=line.rstrip().split(',')
       if len(ll) ==6:  # DAILY UPDATES (not Time)
          dd=strToIso8601TZ(ll[0])
          lst.append(dd)
          lst.append(np.nan)
          lst.append(ll[1])
          lst.append(ll[2])
          lst.append(ll[3])
          lst.append(ll[4])
          lst.append(ll[5])
          lst.append(np.nan)
          lst.append(np.nan)
       elif len(ll) ==7:  # INTRADAY (add Time)
          ## Check the TIme from Kibot
          ttime=splitTime(symb,ll[1])
          hh=ttime[0]
          mm=ttime[1]
          dd =strToIso8601TZ(ll[0],hh,mm)
          lst.append(dd)
          #lst.append(ll[0])
          lst.append(ll[1])
          lst.append(ll[2])
          lst.append(ll[3])
          lst.append(ll[4])
          lst.append(ll[5])
          lst.append(ll[6])
          lst.append(np.nan)
          lst.append(np.nan)
       else: raise  TypeError("Kibot wrong input format: "+ line +" Check che input file")
       return  lst
    except Exception as e:
        print("KiBotParser::parse() Error parsing the line: "+ str(e) +" - Wrong format!")
        lst.append(line)
    return lst


def parseEntryToCDF(file_name, extracted_path, target_date_only=None) -> list:
    #self._logger.info("PyRarFileManager::parseEntryToCDF(): - Parsing file: "+ name)
    cdf=[]
    symb = None
    base=os.path.basename(file_name)
    path=os.path.dirname(file_name)
    if re.match('[A-Z]*[0-9]*.[A-Z]*.txt',base):
        symb = base.replace('.txt', "")
        f_open = extracted_path  +"/" + base
        with open(f_open) as f:
            if target_date_only is not None:
                # Kibot lines start with MM/DD/YYYY,... — pre-filter at read time
                # so full-history refresh files (e.g. AAPL.txt = 4.2M lines) are
                # reduced to just the target date's lines (~390 rows). Avoids
                # ingesting the whole file into memory.
                prefix = target_date_only.strftime('%m/%d/%Y') + ','
                cdf = [parse(line, symb) for line in f if line.startswith(prefix)]
            else:
                cdf=[parse(line,symb) for line in f ]
    else:
             print("PyRarFileManager::parseEntryToCDF(): - Skipped File "+ file_name)
    return cdf, symb

import operator
_validate_ge = partialmethod(_validate_op, op=operator.ge)
_validate_gt = partialmethod(_validate_op, op=operator.gt)


def _create_cdf_file_storage(svectorize_symbol : bool,
                              svectorize_daily  : bool,
                              csv_path : str,
                              csv_prefix : str) -> CSVVectorizedStorage[MarketDataBar]:
        """
        Factory function to create a properly configured storage instance.

        :param svectorize_symbol: Whether to vectorize by symbol
        :param svectorize_daily: Whether to vectorize by date
        :return: Configured CSVVectorizedStorage instance
        """
        vectorize_fields = []
        if svectorize_daily:
            vectorize_fields.append(MarketDataBar.Fields.DATE)
        if svectorize_symbol:
            vectorize_fields.append(MarketDataBar.Fields.SYMB)

        storage = CSVVectorizedStorage(
            schema_class=MarketDataBar,
            vectorize_by=vectorize_fields,
            csv_path=csv_path,
            csv_filename_prefix=csv_prefix)
        return storage


def _parsing_and_writing_cdf(filesToParse : str,
                              workingpath : str,
                              processed_cdf_path : str,
                              is_daily : bool,
                              yyyymmdd : int,
                              processed_earliest_date : date,
                              logger : Logger = None,
                              target_date_only : date = None):
    '''
    parse an extracted kibot to svectorized Cdfs
    :param fileToParse:
    :param workingpath:
    :param processed_cdf_path:
    :param is_daily:
    :param yyyymmdd:
    :return:
    '''
    count = 0
    symbols_to_dates = []

    cdf_storage = _create_cdf_file_storage(svectorize_symbol=True,
                                            svectorize_daily =True,
                                            csv_path=processed_cdf_path,
                                            csv_prefix='')

    for nf in filesToParse:
        try:
            cdf, symb = parseEntryToCDF(nf, workingpath, target_date_only=target_date_only)
            if len(cdf) != 0:
                df = pd.DataFrame(cdf, columns=[MarketDataBar.Fields.DATE,
                                                MarketDataBar.Fields.DATETIME,
                                                MarketDataBar.Fields.OP,
                                                MarketDataBar.Fields.HI,
                                                MarketDataBar.Fields.LO,
                                                MarketDataBar.Fields.CL,
                                                MarketDataBar.Fields.VLM,
                                                MarketDataBar.Fields.VWAP,
                                                MarketDataBar.Fields.COUNT])

                df[MarketDataBar.Fields.DATETIME] = pd.to_datetime(df[MarketDataBar.Fields.DATE])
                df[MarketDataBar.Fields.DATE] = [extract_date(t) for t in df[MarketDataBar.Fields.DATE]]
                #
                if len(df) >= 1:
                    nice = df[MarketDataBar.Fields.DATE] >= processed_earliest_date
                    df = df[nice]
                # If rewrite_history is off the caller passes target_date_only, and we
                # keep only that date's row(s). This avoids thousands of per-date NFS
                # writes per symbol when the archive contains a full-history refresh.
                if target_date_only is not None and len(df) >= 1:
                    df = df[df[MarketDataBar.Fields.DATE] == target_date_only]

                df[MarketDataBar.Fields.SYMB] = symb

                # Write the Cdf files
                cdf_storage.write(df)
                count += 1

                # The symbols to dates written summary
                symbols_to_dates.append({
                    'symb': symb,
                    'dates': len(df[MarketDataBar.Fields.DATE].unique()),
                    'start': df[MarketDataBar.Fields.DATE].min()
                })
                # Log every 250 done.
                if count % 250 == 0:
                    msg = 'Processed {} entries...'.format(count)
                    if logger is not None:
                        logger.info(msg)
                    else:
                        print(msg)

        except Exception as e:
            import traceback
            msg = f"Error processing: {nf}: {type(e).__name__}: {e}"
            if logger is not None:
                logger.error(msg)
                logger.error(traceback.format_exc())
            else:
                print(msg)
                traceback.print_exc()

    processing_summary_file = processed_cdf_path + '/processing_summary_' + str(yyyymmdd) + '.csv'
    pd.DataFrame(symbols_to_dates).to_csv(processing_summary_file)
    return count


# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------
# Kibot Stages
# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------


class KibotDailyFtpDump(BaseStage, AirflowStageMixin):
    """
        Downloads daily Kibot dumps from FTP and validates their presence.
        Can also be used as an AirflowStageMixin.
    """
    kibot_ftp_section = 'Kibot FTP'


    def run(self, ctx: PipelineContext) -> Tuple[StageResult, str]:
        errors : str = None
        outfolder = None
        ctx.logger.info('Starting Kibot Ftp Download with Params: '+ str(configparser_to_json(ctx.params)))
        skip_ftp = False
        try:
            skip_ftp = ctx.params.getboolean('default', 'skip_ftp', fallback=False)
        except Exception:
            skip_ftp = False

        try:
            outfolder  = ctx.params.get(self.kibot_ftp_section, 'outfolder')
            if skip_ftp:
                msg = 'Skipping FTP dump (skip_ftp=true) for KibotDailyFtpDump.'
                ctx.logger.info(msg)
                return (StageResult.SUCCESS, msg)
            ftp_params = FtpWrapperParameters(config_parser=ctx.params,
                                              ftp_section=self.kibot_ftp_section)
            ftp_worker = FtpWrapper(ftp_params,
                                    ctx.logger)
            os.makedirs(outfolder, exist_ok=True)
            ftp_worker.connect_to_ftp()
            # Skip Monthly/ — multi-GB archives our pipeline never consumes; they
            # would hang or timeout the daily FTP step.
            ftp_worker.dump_all_from_ftp('/Updates',
                                         outfolder,
                                         download_only_if_newer=True,
                                         verbose=True,
                                         exclude_dirs=['Monthly'])
        except Exception as e:
            errors = 'Error while running KibotDailyFtpDump ' + self.name + ': ' + str(e)
            ctx.logger.error(errors)

        if outfolder is None:
            return (StageResult.FAIL, 'Missing Kibot FTP configuration. errors: ' + str(errors))

        # Verify if the data was dumped
        rundate = datetime.strptime(
            ctx.params.get('default', 'rundate'), "%Y-%m-%d").date()
        prevdate = prev_business_day(rundate)
        yyyymmdd = prevdate.strftime('%Y%m%d')
        etf_daily_file = outfolder + '/All ETFs/Daily/' + str(yyyymmdd) +'.exe'
        stk_daily_file = outfolder + '/All Stocks/Daily/' + str(yyyymmdd) + '.exe'
        etf_daily_file_exists = os.path.exists(etf_daily_file)
        message = 'Etf file downloaded: ' + str(etf_daily_file_exists)
        stk_daily_file_exists = os.path.exists(stk_daily_file)
        message += '; Stock file downloaded: ' + str(stk_daily_file_exists)
        if stk_daily_file_exists and etf_daily_file_exists:
            if errors == '':
                stage = StageResult.SUCCESS
            else:
                stage = StageResult.SUCCESS_WITH_WARNINGS
        else:
            stage = StageResult.FAIL
        final_msg = message + '. errors: ' + str(errors)
        return (stage, final_msg)


class KibotDailyArchiveExtract(BaseStage, AirflowStageMixin):
    """
        Extracts daily archives once into a shared folder for reuse.
    """
    kibot_process_section = 'Kibot Cdf Processing'

    def run(self, ctx: PipelineContext) -> Tuple[StageResult, str]:
        try:
            shared_extract_root = ctx.params.get('default', 'shared_extract_root', fallback=None)
            if not shared_extract_root:
                msg = "No shared_extract_root configured; skipping archive extraction."
                ctx.logger.info(msg)
                return (StageResult.SUCCESS, msg)

            rundate = datetime.strptime(
                ctx.params.get('default', 'rundate'), "%Y-%m-%d").date()
            target_date = rundate - timedelta(days=1)
            ctx.logger.info(f"Archive extract rundate={rundate} target_date={target_date}")
            if target_date.weekday() >= 5:
                msg = f"Skipping archive extraction on weekend target_date {target_date}."
                ctx.logger.info(msg)
                return (StageResult.SUCCESS, msg)
            archives = set()
            stages_missing_summary = []

            def _collect_missing(params: ConfigParser, label: str) -> None:
                processing_stages = json.loads(params.get(self.kibot_process_section, 'processing_stages'))
                for stg in processing_stages:
                    stage_section = self.kibot_process_section + ' ' + stg
                    archivepath = params.get(stage_section, 'archivepath')
                    archive_in = archivepath + '/' + target_date.strftime('%Y%m%d') + '.exe'
                    processed_cdf_path = params.get(stage_section, 'processed_cdf_path')
                    summary_file = processed_cdf_path + '/processing_summary_' + target_date.strftime('%Y%m%d') + '.csv'
                    ctx.logger.info(
                        f"Summary check label={label} stage={stg} summary_file={summary_file} "
                        f"exists={os.path.exists(summary_file)}"
                    )
                    if os.path.exists(summary_file) and os.path.getsize(summary_file) > 0:
                        continue
                    stages_missing_summary.append(f"{label}:{stg}")
                    archives.add(archive_in)

            _collect_missing(ctx.params, "primary")
            extra_configs = ctx.params.get('default', 'extra_config_paths', fallback='')
            if extra_configs:
                for cfg_path in [p.strip() for p in extra_configs.split(',') if p.strip()]:
                    if not os.path.isfile(cfg_path):
                        ctx.logger.warning(f"Extra config not found: {cfg_path}")
                        continue
                    extra_params = ConfigParser()
                    extra_params.read(cfg_path)
                    if not extra_params.has_section(self.kibot_process_section):
                        ctx.logger.warning(f"Extra config missing section {self.kibot_process_section}: {cfg_path}")
                        continue
                    _collect_missing(extra_params, os.path.basename(cfg_path))

            if not stages_missing_summary:
                msg = "All processing summaries exist; skipping archive extraction."
                ctx.logger.info(msg)
                return (StageResult.SUCCESS, msg)

            # Pre-stage archives from NFS to local disk and extract in parallel.
            # NFS-bottlenecked sequential reads were the main extract cost.
            stage_root = tempfile.mkdtemp(prefix="kibot_stage_")
            ctx.logger.info(f"Staging archives locally under {stage_root}")
            try:
                def _stage_and_extract(archive_in: str) -> str:
                    archive_base = os.path.splitext(os.path.basename(archive_in))[0]
                    source_dir = _extract_subdir_from_archive(archive_in)
                    extract_path = os.path.join(shared_extract_root, source_dir, archive_base)
                    marker = os.path.join(extract_path, ".extracted")
                    if os.path.exists(marker):
                        return f"Archive already extracted: {archive_in}"
                    if not os.path.exists(archive_in):
                        raise FileNotFoundError(f"Archive missing: {archive_in}")
                    os.makedirs(extract_path, exist_ok=True)
                    # Stocks and ETFs archives share the same basename
                    # ("YYYYMMDD.exe"); keep them isolated by source_dir to avoid
                    # one thread's copy clobbering the other's.
                    stage_subdir = os.path.join(stage_root, source_dir)
                    os.makedirs(stage_subdir, exist_ok=True)
                    local_archive = os.path.join(stage_subdir, os.path.basename(archive_in))

                    # Copy from NFS to local with size verification + retry.
                    # Previously a silent NFS short-read or local-disk-full would
                    # produce a truncated local file and 7z would fail with
                    # cryptic "E_FAIL" or "No more files".
                    expected_size = os.path.getsize(archive_in)
                    last_err = None
                    for attempt in range(3):
                        try:
                            shutil.copyfile(archive_in, local_archive)
                            actual = os.path.getsize(local_archive)
                            if actual != expected_size:
                                raise IOError(
                                    f"copy size mismatch for {archive_in}: "
                                    f"src={expected_size} dst={actual} "
                                    f"(NFS short-read or local disk full?). "
                                    f"Free on stage dir: "
                                    f"{shutil.disk_usage(os.path.dirname(local_archive)).free} bytes"
                                )
                            last_err = None
                            break
                        except (OSError, IOError) as e:
                            last_err = e
                            try:
                                os.remove(local_archive)
                            except OSError:
                                pass
                            time.sleep(2 * (attempt + 1))
                    if last_err is not None:
                        raise last_err

                    try:
                        extract_with_7zip(local_archive, extract_path)
                    finally:
                        try:
                            os.remove(local_archive)
                        except OSError:
                            pass
                    with open(marker, "w") as handle:
                        handle.write(datetime.utcnow().isoformat())
                    return f"Extraction complete: {archive_in} -> {extract_path}"

                # 2 archives (stocks + ETFs) -> 2 worker threads is enough.
                with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, len(archives))) as ex:
                    for fut in concurrent.futures.as_completed(
                        [ex.submit(_stage_and_extract, a) for a in archives]
                    ):
                        ctx.logger.info(fut.result())
            finally:
                shutil.rmtree(stage_root, ignore_errors=True)

            return (StageResult.SUCCESS, "Archive extraction complete.")
        except Exception as e:
            errors = 'Error while running KibotDailyArchiveExtract ' + self.name + ': ' + str(e)
            ctx.logger.error(errors)
            return (StageResult.FAIL, errors)


class KibotDailyArchiveCleanup(BaseStage, AirflowStageMixin):
    """
        Cleans up shared extracted archives after processing.
    """
    kibot_process_section = 'Kibot Cdf Processing'

    def run(self, ctx: PipelineContext) -> Tuple[StageResult, str]:
        try:
            if ctx.params.getboolean('default', 'skip_cleanup', fallback=False):
                msg = "skip_cleanup=true; leaving extracted archives in place."
                ctx.logger.info(msg)
                return (StageResult.SUCCESS, msg)
            shared_extract_root = ctx.params.get('default', 'shared_extract_root', fallback=None)
            if not shared_extract_root:
                msg = "No shared_extract_root configured; skipping archive cleanup."
                ctx.logger.info(msg)
                return (StageResult.SUCCESS, msg)

            rundate = datetime.strptime(
                ctx.params.get('default', 'rundate'), "%Y-%m-%d").date()
            target_date = rundate - timedelta(days=1)
            if target_date.weekday() >= 5:
                msg = f"Skipping archive cleanup on weekend target_date {target_date}."
                ctx.logger.info(msg)
                return (StageResult.SUCCESS, msg)
            processing_stages = json.loads(ctx.params.get(self.kibot_process_section, 'processing_stages'))
            archives = set()
            for stg in processing_stages:
                stage_section = self.kibot_process_section + ' ' + stg
                archivepath = ctx.params.get(stage_section, 'archivepath')
                archive_in = archivepath + '/' + target_date.strftime('%Y%m%d') + '.exe'
                archives.add(archive_in)

            for archive_in in archives:
                archive_base = os.path.splitext(os.path.basename(archive_in))[0]
                source_dir = _extract_subdir_from_archive(archive_in)
                extract_path = os.path.join(shared_extract_root, source_dir, archive_base)
                shutil.rmtree(extract_path, ignore_errors=True)
                ctx.logger.info(f"Cleaned extracted archive at {extract_path}")

            return (StageResult.SUCCESS, "Archive cleanup complete.")
        except Exception as e:
            errors = 'Error while running KibotDailyArchiveCleanup ' + self.name + ': ' + str(e)
            ctx.logger.error(errors)
            return (StageResult.FAIL, errors)



class KibotCdfProcessor(BaseStage, AirflowStageMixin):

    kibot_process_section = 'Kibot Cdf Processing'

    process_earliest_daily  : date = datetime.strptime('2016-01-01', '%Y-%m-%d').date()
    process_earliest_intra  : date = datetime.strptime('2019-01-01', '%Y-%m-%d').date()

    def _process_kibot_archive(self, archive_in: str,
                                     working_path: str,
                                     processed_cdf_path : str,
                                     daily : bool,
                                     logger: Logger = None,
                                     pre_extracted_path: str = None,
                                     cleanup: bool = True,
                                     target_date_only: date = None) -> (bool, str):
        yyyymmdd = extract_and_validate_date(archive_in)
        if yyyymmdd is None:
            return (False, 'The archive in could not be parsed to a valid date: ' + archive_in)
        try:
            # Create Historical Local Directory
            if pre_extracted_path and os.path.isdir(pre_extracted_path):
                working_path = pre_extracted_path
            if not os.path.exists(working_path): os.makedirs(working_path)
            count = 0
            try:
                if pre_extracted_path and os.path.isdir(pre_extracted_path):
                    logger.info("Using pre-extracted archive at " + working_path)
                else:
                    if not os.path.exists(archive_in):
                        return (False, f"Archive missing: {archive_in}")
                    extract_with_7zip(archive_in, working_path)
                outpath = processed_cdf_path + '/' + str(yyyymmdd)
                os.makedirs(outpath, exist_ok=True)
                # Parse the daily
                if daily:
                    fileToParse_Daily = os.listdir(working_path + "/Daily")
                    count = _parsing_and_writing_cdf(fileToParse_Daily,
                                                       working_path + "/Daily",
                                                       processed_cdf_path,
                                                       is_daily=True,
                                                       yyyymmdd=int(yyyymmdd),
                                                       processed_earliest_date=self.process_earliest_daily,
                                                       logger=logger,
                                                       target_date_only=target_date_only)

                else:
                    fileToParse_Intra = os.listdir(working_path + "/Intraday")
                    count = _parsing_and_writing_cdf(fileToParse_Intra,
                                                       working_path + "/Intraday",
                                                       processed_cdf_path,
                                                       is_daily=False,
                                                       yyyymmdd=int(yyyymmdd),
                                                       processed_earliest_date=self.process_earliest_intra,
                                                       logger=logger,
                                                       target_date_only=target_date_only)
            except Exception as e:
                print(f"Error extracting or parsing: {e}")
            finally:
                if cleanup:
                    shutil.rmtree(working_path, ignore_errors=True)
                pass
        except Exception as e:
            return (False, str(e))
        if count < 1500:
            return (False, f"Processed too few files ({count}) for {archive_in}")
        return (True, 'Processed: ' + str(count))


    def run(self, ctx: PipelineContext) -> Tuple[StageResult, str]:
        errors: str = None
        ctx.logger.info('Starting Kibot Cdf Processing with Params: ' + str(configparser_to_json(ctx.params)))

        try:
            processing_stages = json.loads(ctx.params.get(self.kibot_process_section, 'processing_stages'))
            stages_override = ctx.params.get('default', 'processing_stages_override', fallback=None)
            if stages_override:
                if isinstance(stages_override, (list, tuple)):
                    processing_stages = list(stages_override)
                else:
                    parsed = None
                    try:
                        parsed = json.loads(stages_override)
                    except Exception:
                        try:
                            parsed = ast.literal_eval(stages_override)
                        except Exception:
                            parsed = None
                    if isinstance(parsed, (list, tuple)):
                        processing_stages = [str(s).strip() for s in parsed]
                    elif isinstance(parsed, str):
                        processing_stages = [parsed.strip()]
                    else:
                        processing_stages = [s.strip() for s in str(stages_override).split(",") if s.strip()]
            rundate = datetime.strptime(
                        ctx.params.get('default', 'rundate'), "%Y-%m-%d").date()
            target_date = rundate - timedelta(days=1)
            if target_date.weekday() >= 5:
                msg = f"Skipping CDF processing on weekend target_date {target_date}."
                ctx.logger.info(msg)
                return (StageResult.SUCCESS, msg)
            shared_extract_root = ctx.params.get('default', 'shared_extract_root', fallback=None)
            # When rewrite_history is False (default), CDFs are written only for
            # target_date — preventing thousands of per-date NFS writes whenever
            # the archive contains a full-history refresh (AAPL/SPY/QQQ pattern).
            rewrite_history = ctx.params.getboolean('default', 'rewrite_history', fallback=False)
            target_date_only = None if rewrite_history else target_date
            ctx.logger.info(f"rewrite_history={rewrite_history} target_date_only={target_date_only}")
            success = True
            messages = []
            for stg in processing_stages:
                ctx.logger.info('Starting Stage: ' + str(stg))
                stage_section = self.kibot_process_section + ' ' + stg
                processed_cdf_path  = ctx.params.get(stage_section, 'processed_cdf_path')
                archivepath = ctx.params.get(stage_section, 'archivepath')
                workingfolder = ctx.params.get(stage_section, 'workingfolder')
                daily = ctx.params.getboolean(stage_section, 'daily')
                archive_in = archivepath + '/' + target_date.strftime('%Y%m%d') + '.exe'
                shared_extract_path = None
                if shared_extract_root:
                    archive_base = os.path.splitext(os.path.basename(archive_in))[0]
                    source_dir = _extract_subdir_from_archive(archive_in)
                    shared_extract_path = os.path.join(shared_extract_root, source_dir, archive_base)
                    workingfolder = shared_extract_path
                summary_file = processed_cdf_path + '/processing_summary_' + target_date.strftime('%Y%m%d') + '.csv'
                if os.path.exists(summary_file) and os.path.getsize(summary_file) > 0:
                    msg = f"Skipping stage {stg}; summary already exists: {summary_file}"
                    ctx.logger.info(msg)
                    continue

                msg = 'Processing archive_in: ' + archive_in + ', workingfolder: ' + workingfolder + ', daily: ' + str(daily)
                ctx.logger.info(msg)

                success_stg, message_stg = self._process_kibot_archive(archive_in,
                                                                   workingfolder,
                                                                   processed_cdf_path,
                                                                   daily,
                                                                   logger=ctx.logger,
                                                                   pre_extracted_path=shared_extract_path,
                                                                   cleanup=(shared_extract_root is None),
                                                                   target_date_only=target_date_only)
                success = success and success_stg
                messages.append(message_stg)

            if success:
                return (StageResult.SUCCESS, "; ".join(messages))
            else:
                return (StageResult.FAIL, "; ".join(messages))

        except Exception as e:
            errors = 'Error while running KibotDailyFtpDump ' + self.name + ': ' + str(e)
            ctx.logger.error(errors)
            return (StageResult.FAIL, "; ".join(messages) + ' -> '  + errors)
